/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursemanagementsoftware;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ritz619
 */
public class ChangeDetails extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form ChangeDetails
     */
    
    private int index;
    private int sindex;
    private ArrayList<ArrayList<Courses>> cpar;
    private ChangeDetails cd;
    private MainGUI mg;

    public void setMg(MainGUI mg) {
        this.mg = mg;
    }
    
    public ChangeDetails() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date.setFormats(dateFormat);
    }

    public void setSindex(int sindex) {
        this.sindex = sindex;
    }

    public void setCpar(ArrayList<ArrayList<Courses>> cpar) {
        this.cpar = cpar;
    }
    
    public final void showDetails(){
        ArrayList<Courses> temp = cpar.get(sindex);
        name.setText(temp.get(index).getName());
        Date.getEditor().setText(temp.get(index).getDate());
        duration.setText("" + temp.get(index).getDuration());
        Fees.setText("" + temp.get(index).getFee());
    }

    public void setIndex(int index) {
        this.index = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        Fees = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Date = new org.jdesktop.swingx.JXDatePicker();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Details: Courses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Ubuntu Medium", 0, 15)); // NOI18N

        jLabel2.setText("Name: ");

        jLabel1.setText("Start Date (dd/mm/yyyy) :");

        jLabel3.setText("Duration:");

        jLabel4.setText("Fees:");

        jButton1.setText("Change Coordinator Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Change Instructor Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Change Participant Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save Changes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(duration)
                            .addComponent(Fees, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Courses c = cpar.get(sindex).get(index);
        Object[] possibilities = new Object[c.getFacs().size()];
        for(int i = 0; i < c.getFacs().size(); i++){
            possibilities[i] = i + 1 + " " + c.getFacs().get(i).getName();
        }
        if(c.getFacs().isEmpty()){
            JOptionPane.showMessageDialog(cd, "No Instructors present");
            return;
        }
        String s = (String)JOptionPane.showInputDialog(
                            cd,
                            "Choose Instructor",
                            "Input",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            possibilities,
                            "ham");
        if(s==null)
            return;
        int k = Integer.parseInt(s.split(" ")[0]) - 1;
        Change w = new Change();
        w.setNum(k);
        cd.setVisible(false);
        w.setMode(4);
        w.setMg(mg);
        w.setCd(cd);
        w.setCmn(w);
        w.setCpar(cpar);
        w.setSindex(sindex);
        w.setIndex(index);
        w.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setCd(ChangeDetails cd) {
        this.cd = cd;
    }
    
    public boolean validDate(String Date){
        String pattern = "[0-3][0-9]/[0-1][0-9]/[0-9]{4}";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(Date);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if(!m.find()){
            JOptionPane.showMessageDialog(cd, "Enter a valid date");
            return false;
        }
        else
            return true;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Courses o = cpar.get(sindex).get(index);
        String coursename = name.getText();
        if(coursename.isEmpty()){
            JOptionPane.showMessageDialog(cd, "Enter Course Name");
            return;
        }
        String date = null;
        try{
            date = Date.getEditor().getText();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(cd, "Please write date in proper format");
            return;
        }
        if(!validDate(date))
            return;
        int courseyear = Integer.parseInt(date.split("/")[2]);
        int session = Integer.parseInt(o.getDate().split("/")[2]);
        if(session!=courseyear){
            JOptionPane.showMessageDialog(cd, "You cannot change course session");
            return;
        }
        Integer dur;
        try{
            dur = Integer.parseInt(duration.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(cd, "Enter an integer for duration");
            duration.setText("");
            return;
        }
        if(dur<1 || dur > 14){
            JOptionPane.showMessageDialog(cd, "Enter an integer between 0 and 15");
            duration.setText("");
            return;
        }
        Integer fees;
        try{
            fees = Integer.parseInt(Fees.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(cd, "Enter an integer for Fees");
            Fees.setText("");
            return;
        }
        o.setName(coursename);
        o.setDate(date);
        o.setDuration(dur);
        o.setFee(fees);
        cd.dispose();
        mg.setVisible(true);
        mg.displayCourses();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Change c = new Change();
        cd.setVisible(false);
        c.setMode(3);
        c.setMg(mg);
        c.setCd(cd);
        c.setCmn(c);
        c.setCpar(cpar);
        c.setSindex(sindex);
        c.setIndex(index);
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Courses c = cpar.get(sindex).get(index);
        Object[] possibilities = new Object[c.getParts().size()];
        for(int i = 0; i < c.getParts().size(); i++){
            possibilities[i] = i + 1 + " " + c.getParts().get(i).getName();
        }
        if(c.getParts().isEmpty()){
            JOptionPane.showMessageDialog(cd, "No Participants present");
            return;
        }
        String s = (String)JOptionPane.showInputDialog(
                            cd,
                            "Choose Participant",
                            "Input",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            possibilities,
                            "ham");
        if(s==null)
            return;
        int k = Integer.parseInt(s.split(" ")[0]) - 1;
        Change w = new Change();
        w.setNum(k);
        cd.setVisible(false);
        w.setMode(5);
        w.setMg(mg);
        w.setCd(cd);
        w.setCmn(w);
        w.setCpar(cpar);
        w.setSindex(sindex);
        w.setIndex(index);
        w.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Date;
    private javax.swing.JTextField Fees;
    private javax.swing.JTextField duration;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
